@startuml
!include Style.puml
skinparam ArrowFontStyle plain

box Parser
participant ":Parser" as PARSER PARSER_COLOR
participant ":ParseResource*" as PARSERESOURCE PARSER_COLOR
participant ":ParseResource" as PARSE PARSER_COLOR
end box

box Command
participant ":CommandResult" as COMMANDRESULT COMMAND_COLOR
participant ":AddCommand" as ADDCOMMAND COMMAND_COLOR
end box

participant ":CreateResource*" as CREATE CREATE_COLOR

activate PARSER PARSER_COLOR
PARSER -[PARSER_COLOR]> ADDCOMMAND : execute(UserInput)
activate ADDCOMMAND COMMAND_COLOR

ADDCOMMAND -[COMMAND_COLOR]> PARSER : parseAddCommand(UserInput)
PARSER --[PARSER_COLOR]> ADDCOMMAND : tag: String

alt resource*
    ADDCOMMAND -[COMMAND_COLOR]> ADDCOMMAND : addResource*(UserInput, container)
    activate ADDCOMMAND COMMAND_COLOR

    ADDCOMMAND -[COMMAND_COLOR]> PARSERESOURCE : parseAddResource*(UserInput)
    activate PARSERESOURCE PARSER_COLOR

    PARSERESOURCE -[PARSER_COLOR]> PARSERESOURCE : parseResource*Args(UserInput)
    activate PARSERESOURCE PARSER_COLOR

    PARSERESOURCE -[PARSER_COLOR]> PARSE : parseIsbn(UserInput)
    activate PARSE PARSER_COLOR
    PARSE --[PARSER_COLOR]> PARSERESOURCE
    deactivate PARSE

    PARSERESOURCE -[PARSER_COLOR]> PARSE : parseTitle(UserInput)
    activate PARSE PARSER_COLOR
    PARSE --[PARSER_COLOR]> PARSERESOURCE
    deactivate PARSE

    PARSERESOURCE -[PARSER_COLOR]> PARSE : parseTag(UserInput)
    activate PARSE PARSER_COLOR
    PARSE --[PARSER_COLOR]> PARSERESOURCE
    deactivate PARSE

    PARSERESOURCE -[PARSER_COLOR]> PARSE : parseStatus(UserInput)
    activate PARSE PARSER_COLOR
    PARSE --[PARSER_COLOR]> PARSERESOURCE : isStatusPresent: Boolean
    deactivate PARSE

    PARSERESOURCE --[PARSER_COLOR]> PARSERESOURCE : isOptionalMatching: Boolean[]
    deactivate PARSERESOURCE

    PARSERESOURCE -[PARSER_COLOR]> PARSERESOURCE : checkEmptyResource*Args(UserInput)
    activate PARSERESOURCE PARSER_COLOR
    PARSERESOURCE --[PARSER_COLOR]> PARSERESOURCE
    deactivate PARSERESOURCE

    PARSERESOURCE --[PARSER_COLOR]> ADDCOMMAND : values: String[]

    ADDCOMMAND -[COMMAND_COLOR]> CREATE : createResource*(values, resourceID)
    activate CREATE CREATE_COLOR
    CREATE --[CREATE_COLOR]> ADDCOMMAND : newResource*: Resource*
    deactivate CREATE

    ADDCOMMAND -[COMMAND_COLOR]> PARSERESOURCE : resetResource*Args()
    PARSERESOURCE --[PARSER_COLOR]> ADDCOMMAND
    deactivate PARSERESOURCE

    ADDCOMMAND --[COMMAND_COLOR]> ADDCOMMAND
    deactivate ADDCOMMAND

    create COMMANDRESULT
    ADDCOMMAND -[COMMAND_COLOR]> COMMANDRESULT : feedbackToUser: String

    activate COMMANDRESULT COMMAND_COLOR
    COMMANDRESULT --[COMMAND_COLOR]> PARSER
    deactivate COMMANDRESULT

else else
    ADDCOMMAND --[COMMAND_COLOR]> PARSER
    deactivate ADDCOMMAND
end

deactivate PARSER

@enduml