@startuml
!include Style.puml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>

skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
participant ":UI" as UI UI_COLOR
participant ":FindCommand" as FINDCOMMAND COMMAND_COLOR
participant ":GenericList<Resource, Event>" as GENERICLIST STORAGE_COLOR
participant ":Resource" as RESOURCE PARSER_COLOR

user -[USER_COLOR]> UI : "find '/t Title1'"
activate UI UI_COLOR

UI -[UI_COLOR]> FINDCOMMAND : execute()
activate FINDCOMMAND COMMAND_COLOR

FINDCOMMAND -[COMMAND_COLOR]> FINDCOMMAND: parseArgument()
activate FINDCOMMAND COMMAND_COLOR
FINDCOMMAND --[COMMAND_COLOR]> FINDCOMMAND: String[] values
deactivate FINDCOMMAND COMMAND_COLOR

FINDCOMMAND -[COMMAND_COLOR]> FINDCOMMAND: validateStatement(values)
activate FINDCOMMAND COMMAND_COLOR
FINDCOMMAND --[COMMAND_COLOR]> FINDCOMMAND: return
deactivate FINDCOMMAND COMMAND_COLOR

alt allValuesNull
    FINDCOMMAND --[COMMAND_COLOR]> UI: INVALID_ARGUMENT_MESSAGE
else !allValuesNull
    FINDCOMMAND -[COMMAND_COLOR]> GENERICLIST: getResourcesList()
    activate GENERICLIST STORAGE_COLOR
    GENERICLIST --[STORAGE_COLOR]> FINDCOMMAND: List<Resource> resources
    deactivate GENERICLIST STORAGE_COLOR
    destroy GENERICLIST

    loop for each Resource in resources
        FINDCOMMAND -[COMMAND_COLOR]> RESOURCE: isResourceMatch(values)
        activate RESOURCE PARSER_COLOR
        RESOURCE --[PARSER_COLOR]> FINDCOMMAND: boolean match
        deactivate RESOURCE PARSER_COLOR
        destroy RESOURCE

        alt match
            FINDCOMMAND -[COMMAND_COLOR]> FINDCOMMAND : Add to matchedResources
        end
    end

    FINDCOMMAND --[COMMAND_COLOR]> UI: displayResults(matchedResources)
    deactivate UI UI_COLOR
    deactivate FINDCOMMAND COMMAND_COLOR
    destroy FINDCOMMAND
    destroy UI
end

@enduml
